# See: https://pre-commit.com/
default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length", "80"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: ["--filename=.flake8"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: detect-private-key
